### ISSUE TITLE
[EPIC] Plans for beta

### ISSUE THREAD

**Issue by matmair** [invenhost/inventree-federation#3]
The following things should be implemented before the alpha can be released

```[tasklist]
### Tasks
- [ ] UC 1: Federation setup
- [ ] UC 2: Party A sends item to party B
- [ ] UC 3: Party B request item from party A
- [ ] UC 4: Party x requests inventory stats from party x 
- [ ] UC 5: Federation stop
```
